### ISSUE TITLE
inx not idx

### ISSUE THREAD

**Issue by Neon22** [lingo/inkscape_onionskin#1]
The docs use the term idx. I think you mean inx ?
Traditionally no installer - instructions need to say - add to share/extensions folder.

**Comment by su-v** [comment]
> Traditionally no installer - instructions need to say - add to share/extensions folder.

Traditionally, the shared extensions folder needs admin/sudo priviledges - it's ok to install custom extensions per user into the extensions directory of the inkscape user profile (thus it will also survive a reinstall or update of the application).

Linux/OS X: `$HOME/.config/inkscape/extensions/`
Windows: `%APPDATA%\inkscape\extensions\`

**Comment by lingo** [comment]
Will fix, I keep typing idx by mistake.

**Comment by lingo** [comment]
Fixed typo.  I don't quite understand regarding the docs; there's a section on what files to copy where.  Is this information not clear?
